### ISSUE TITLE
Sjasmplus list files does not work

### ISSUE THREAD

**Issue by ruguevara** [maziac/z80-debug#2]
First of all: really great work, I'm impressed with well structured code and smart async architecture of extension!

I tried to load sjasmplus list file into debugger and it seems to not working, I'm getting opened `disasm.asm` instead of source file.

I looked into code of current version from extensions marketplace and have not found any occurrences of string "sjasmplus". And in `master` branch there is some conditions on it. But master branch seems to not loading source files even in `z80asm` mode for .list files.

**Comment by maziac** [comment]
Which version have you used?

**Comment by ruguevara** [comment]
In version 0.6.2 sjasmplus list file does not work.
In current master (commit 8a788cb8) z80asm list files do not work either.

**Comment by maziac** [comment]
I have not released the version that supports sjasmplus yet.  Have you built the current master by yourself?Could you attach your launch.json?Am 24.01.2019 15:46 schrieb ruguevara <notifications@github.com>:I tried to load sjasmplus list file into debugger and it seems to not working, I'm getting opened disasm.asm instead of source file.
I looked into code of current version from extensions marketplace and have not found any occurrences of string "sjasmplus". And in master branch there is some conditions on it. But master branch seems to not loading source files even in z80asm mode.

**Comment by ruguevara** [comment]
Wow! After I cleaned my launch.json magic happened — it worked! I'm sorry for being bothering you with this issue.

Thank you for the valuable advice to pay attach my launch.json and for great work on this extension!

**Comment by maziac** [comment]
Good to hear that it works now.Let me know if you find any other problems.Am 25.01.2019 08:38 schrieb ruguevara <notifications@github.com>:Wow! After I cleaned my launch.json magic happened — it worked! I'm sorry for being bothering you with this issue.

Thank you for the valuable advice to pay attach my launch.json and for great work on this extension!
