### ISSUE TITLE
Use with Busraider question

### ISSUE THREAD

**Issue by robdobsn** [maziac/z80-debug#4]
I'm working with your code to provide debug for a 'real' retro computer add-on called BusRaider for RC2014 https://github.com/robdobsn/PiBusRaider which I designed. I have a few questions and would like to ask a few questions if possible but can't see another means to contact you. My questions are mainly around listing files and breakpoint support.

**Comment by maziac** [comment]
No problem.
Either ask here or send me your email address.

**Comment by robdobsn** [comment]
My email is rob@dobson.com

**Comment by robdobsn** [comment]
Hi

Regarding the Z80 Debug VS Code plugin. I haven't managed to get the list format feature working. Also there is a reference to a rom listing for the spectrum in the launch.json file - is this something you created in the right format? If so would you be OK to share this?

Thanks

Rob

Rob Dobson FIET
rob@dobson.com
+44 7770 866452
http://LinkedIn.com/in/robdobsn
@robdobsn www.robdobson.com

**Comment by maziac** [comment]
Hi Rob,

I haven't used that file for some time since the z80-debug now also contains a disassembler and can disassemble the ROM 
or other unused areas on the fly.
But, of course, sometimes it  makes sense to use the commented listing.

I attached it (and the 128 ROM listings) below.

Meanwhile I also changed the default assembler format to "sjasmplus" so you certainly have to change it in the launch.json:
"asm": "z80asm",

The zip also contains the labels files, just for completeness, you don't need them for z80-debug (it will generate the labels from the list file).

Please let me know if you have any other problem or if the documentation is wrong or outdated.

Cheers,
Thomas




You can find the original files here:
https://www.tablix.org/~avian/spectrum/rom/
but I may have changed the one or the other line so that it fits the z80-debug better.
